globalVariables(c("#Org_Code", ".", "Activity_ID", "Analysis_Start_Date",
                "Analysis_Start_Time", "Analysis_Start_Time_Zone",
                "Analytical_Method_ID", "Analytical_Method_ID_Context",
                "Analytical_Remark", "Bias", "Biological_Individual_ID",
                "Biological_Intent", "Cell_Form", "Cell_Shape",
                "Characteristic_Name", "Confidence_Interval",
                "Data_Logger_Line_Name", "Dilution_Factor", "dups", "EndDate",
                "File_Name_or_Resource_ID", "Filtered_Fraction",
                "Frequency_Class_Bounds_Unit_1",
                "Frequency_Class_Bounds_Unit_2",
                "Frequency_Class_Bounds_Unit_3", "Frequency_Class_Descriptor_1",
                "Frequency_Class_Descriptor_2", "Frequency_Class_Descriptor_3",
                "Frequency_Class_Lower_Bound_1",
                "Frequency_Class_Lower_Bound_2",
                "Frequency_Class_Lower_Bound_3",
                "Frequency_Class_Upper_Bound_1",
                "Frequency_Class_Upper_Bound_2",
                "Frequency_Class_Upper_Bound_3", "Functional_Feeding_Group_1",
                "Functional_Feeding_Group_2", "Functional_Feeding_Group_3",
                "Group_Summary_Count_or_Weight",
                "Group_Summary_Count_or_Weight_Unit", "Habit_Name_1",
                "Habit_Name_2", "Habit_Name_3",
                "Lab_Accreditation_Authority_Name",
                "Lab_Accreditation_Indicator", "Lab_Batch_ID", "Lab_ID",
                "Lab_Remark_Code", "Lab_Reported_Result",
                "Lab_Sample_Preparation_ID",
                "Lab_Sample_Preparation_Start_Date",
                "Lab_Sample_Preparation_Start_Time",
                "Lab_Sample_Preparation_Start_Time_Zone", "Limit_Comment",
                "Logger_Percent_Error", "Logger_Standard_Difference",
                "Lower_Confidence_Limit", "Lower_Quantification_Limit",
                "Method_Detection_Limit", "Method_Speciation",
                "Num_of_Replicates", "Particle_Size_Basis",
                "Pollution_Tolerance", "Pollution_Tolerance_Scale", "Precision",
                "Predicted_Result", "Reportable_Result",
                "Resource_Creator_Name", "Resource_Date",
                "Resource_Publication_Year", "Resource_Publisher_Name",
                "Resource_Subject_Text", "Resource_Title_Name",
                "Resource_Volume_Pages", "Result_Comment",
                "Result_Depth_Altitude_Reference_Point",
                "Result_Depth_Height_Measure",
                "Result_Depth_Height_Measure_Unit",
                "Result_Detection_Condition", "Result_File_Name",
                "Result_Qualifier", "Result_Sampling_Point_Name",
                "Result_Status", "Result_Text", "Result_Type", "Result_Unit",
                "Source_Flags", "StartDate", "Statistical_Basis",
                "Subject_Taxon", "Taxonomist_Accreditation_Authority_Name",
                "Taxonomist_Accreditation_Indicator", "Temperature_Basis",
                "Time_Basis", "Tissue_Anatomy", "Trophic_Level",
                "Unidentified_Species_ID", "Upper_Confidence_Limit",
                "Upper_Quantification_Limit", "Voltinism", "Weight_Basis",
                "address", "analysis", "analyte_code", "assessment",
                "comparison", "flag", "input_file_name", "is_blank",
                "lab_number", "meta", "orig_text", "param", "param_description",
                "parameter", "qa_description", "qa_within_precision_limits",
                "repeat_measurement", "sheet", "unit", "value",
                "within_precision_limits"))
